version: '3'
services:
  mysql:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: change_name_to_whatever_you_want
    ports:
      - "3309"
    volumes:
      - db_data:/var/lib/mysql
  web:
    depends_on:
      - mysql 
    build: .
    ports:
      - "8999:80"
#Build Volumes
volumes:
    db_data:

